name: CI/CD Pipeline

# รัน pipeline เมื่อมีการ push หรือ pull request ไปยัง branch 'main'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run Linting (ตรวจสอบรูปแบบโค้ด)
      - name: Run Linting
        run: npm run lint

      # 5. Run Unit Tests (ทดสอบส่วนย่อยของโปรเจค)
      - name: Run Unit Tests
        run: npm test -- --coverage

      # 6. Run Integration Tests (ทดสอบการทำงานร่วมกันของโมดูล)
      - name: Run Integration Tests
        run: npm run integration-test

      # 7. Run E2E Tests (ทดสอบการทำงานของแอปแบบ End-to-End)
      - name: Run E2E Tests
        run: npm run e2e

      # 8. Run Security Check (ตรวจสอบช่องโหว่ของ dependencies)
      - name: Run Security Check
        run: npm audit

      # 9. Build Project (สร้างโปรเจคเพื่อให้แน่ใจว่าไม่มีข้อผิดพลาด)
      - name: Build project
        run: npm run build

      # 10. Upload code coverage (อัปโหลดผลลัพธ์ของการทดสอบโค้ด)
      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/*.json

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && success()

    steps:
      # 11. Checkout repository (สำหรับการ deploy)
      - name: Checkout repository
        uses: actions/checkout@v2

      # 12. Deploy to GitHub Pages (อัปโหลดไฟล์ไปที่ GitHub Pages)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

  # 13. Notifications (การแจ้งเตือนเมื่อ pipeline เสร็จสิ้น)
  notify:
    runs-on: ubuntu-latest
    needs: [build-and-test, deploy]
    steps:
      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2      
        with:
          message: |
            🎉 Build & Deploy Completed Successfully!
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}
            See the results: ${{ github.repository }}
