name: Lint, Unit Test, Cypress Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run HTML Linting for docs folder
        run: npx htmlhint "docs/**/*.html"
        continue-on-error: true # ถ้ามีข้อผิดพลาดจะยังคงทำงานต่อ

  unit-test:
    runs-on: ubuntu-latest
    needs: lint # รอ job lint ทำงานเสร็จ

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test
        continue-on-error: true # ถ้ามีข้อผิดพลาดจะยังคงทำงานต่อ

  cypress-test:
    runs-on: ubuntu-latest
    needs: unit-test # รอ job unit-test ทำงานเสร็จ

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Create Cypress configuration file
        run: |
          echo '{' > cypress.json
          echo '  "baseUrl": "http://localhost:3000",' >> cypress.json
          echo '  "integrationFolder": "cypress/integration",' >> cypress.json
          echo '  "fixturesFolder": "cypress/fixtures",' >> cypress.json
          echo '  "video": false' >> cypress.json
          echo '}' >> cypress.json

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
        continue-on-error: true
