name: Lint, Unit Test, and E2E Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Verify htmllint installation
        run: npx htmllint --version

      - name: Run HTML Linting
        run: npm run lint:html
        continue-on-error: true # ถ้ามีข้อผิดพลาดจะยังคงทำงานต่อ

  unit-test:
    runs-on: ubuntu-latest
    needs: lint # รอ job lint ทำงานเสร็จ
    continue-on-error: true # ถ้ามีข้อผิดพลาดจะยังคงทำงานต่อ
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test

  e2e-test:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Serve HTML files
        run: npx serve docs -l 8080 &

      - name: Wait for server to start
        run: sleep 5

      - name: Run Cypress Tests
        run: npx cypress run --spec 'cypress/integration/**/*.js'

      - name: Save Cypress Videos and Screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Save Cypress Logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-logs
          path: cypress/logs
